### ISSUE TITLE
Log entry every 3-5 seconds

### ISSUE THREAD

**Issue by tiamat2012** [crowbarmaster/BedrockManagementService#13]
I don't know what triggered it, but I am getting "Server stopped successfully." in the service log every 3-5 seconds.

I did delete the Default server/world and create a new server/world, so I am wondering if there is some registry or other setting stuck in the service that is generating the log.  I don't know if it was happening after the first install.  I did try to uninstall the service and reinstall it, but it didn't stop the logs.

This will fill up disk space eventually and it causes some visual repaints in the client log screen, so I tried to disable the LogServiceToFile setting in the global service setting, but that hung the client and I could not stop the server.  But after a reboot, that line is not appearing in the service logs screen in the client (but other entries are, so I am not quite clear what that setting enables or disables).  Anyway, it might just be a debug output left in some watchdog timer check.

**Comment by crowbarmaster** [comment]
Sounds like you nailed it on the head with "stuck in the service". Sounds like the old watchdog service for the default server didn't close. Each server process gets its own watchdog, it also doubles as start and stop control. I will run through the tests again in the morning and try to reproduce this!
