### ISSUE TITLE
Folder names in the ZIP file

### ISSUE THREAD

**Issue by tiamat2012** [crowbarmaster/BedrockManagementService#16]
Please rename the folders in the top of the ZIP file when you build it for a release.

net6.0 and net6.0-windows are not very helpful.  I rename them to client and server after I extract them.  But people who are new to this application will be confused, and they may not look at the filenames closely enough to see one is a client and one is the server.  They will probably think they are duplicated folders accidentally left in the ZIP file.

**Comment by crowbarmaster** [comment]
I am actually going to pin this one for a while 🤣 

Back in the old .NET Framework days, Client and server would co-mingle in one output folder. With .NET Core targeting multiple platforms now, I get these target folders in the directory now. This is 100% not my intention. I will create a method to auto-rename and package builds in the future to avoid this again.

**Comment by crowbarmaster** [comment]
Publishing setup, and directories have been merged again, as well as packed exe files to clean up the structure quite a bit. Closing this!
