### ISSUE TITLE
Need to include pack enabler json files with backups.

### ISSUE THREAD

**Issue by crowbarmaster** [crowbarmaster/BedrockManagementService#19]
Hi.  Everything is working fine with 2.55.  I have a very tricky config running right now on a Mac bootcamp windows 10 setup at a hotel.  I haven’t been able to reply to any of your closure notes until tonight.  It took quite a while to get firewalls, ICS, a tiny Wi-Fi hotspot device, Xbox and iPads on the private Wi-Fi, and bridging/routing the hotel Wi-Fi to all work out just right, so I am not going to touch it and try 2.56 until I get back home.

The only gap is related to this issue.  The backup is working great with no downtime backups, but the world_*_packs.json files are not backed up or restored.  You could say this was a bug with the save query output not including these files, but when I restore a backup, the resource packs get deactivated.  I can manually restore this file from my own backup and restart the server, but ideally you could include these json files in the backup and restore process.

_Originally posted by @tiamat2012 in https://github.com/crowbarmaster/BedrockManagementService/issues/9#issuecomment-999263067_

**Comment by crowbarmaster** [comment]
I will implement this soon! I am actually spending time building a reusable method for handling Json files. In the end it should be much easier to handle these files through the service. What I have now is a mess. However, I should be able to stash my work, and apply that quick. I really just need to grab the folder like old times, and overwrite with the queried file contents.

**Comment by tiamat2012** [comment]
2.56.8031.12492 backed up the world_resource_packs.json file.  I cannot close this issue since you opened it., but it appears to be fixed.
