### ISSUE TITLE
Service does not appear to use conf files

### ISSUE THREAD

**Issue by tiamat2012** [crowbarmaster/BedrockManagementService#20]
Hi,

Merry Christmas and Happy New Year.

Next week after the holiday weekend, please look at problems related to copying all the files from one server to another.  It took me quite a while to get the Windows 10 laptop working with my world that was running on my server at home.  I chalked it up to the difficult setup I was running in the hotel.

But I am home again, and I wanted to just copy-paste all the files to the server from Windows 10 (uninstalled the old service version and removed all the old files on the server before I started) and start the service and expect it would read all the configuration files and everything would work out fine.  But that is not the case.  It seems the service or something is keeping configurations and settings outside of the conf files.  So like on the Windows 10 laptop, I have to rebuild everything from scratch, configuring the globals to different folders for the ServersPath and BackupPath, creating a fresh install for my world settings (delete the Default world, create the new world with the right settings, install packs, etc) and then stop the server, copy over just my world folder, and then restart.

As far as I can tell, the service didn't even try to read the globals.conf file or the existing conf file for my world.  It seems to keep a shadow configuration somewhere (the registry?) and it didn't find what it was looking for, so it defaulted everything to a fresh install.  This seems to happen each time I update the version as well, and I bet it's because I uninstall  the service of the old version and then reinstall the service for the new version to do testing and it's resetting something somewhere.  It may also explain something really weird that happened a few weeks ago, where I was able to run the server on the command line and it ran under a completely different config than when I started the service.

**Comment by crowbarmaster** [comment]
Yeah, this was a strange issue that came about after I started packing to single executables. If you are still using 2.55, then you will find some files kicking around in your C:\windows\system32 folder. If you hadn't already, 2.56 Beta was quickly released with an addressed fix to this. Also, if you could, the latest debug edition is labeled as pre-release, and the quick link to the "latest" wont take you there. You need to go back to the releases folder, and you will see it then. A link just in case: [https://github.com/crowbarmaster/BedrockManagementService/releases/tag/latest](url). This will build on commit, so it's always possible something is broken. I am going to leave 2.56Beta as the last and current "stable" beta for now.

**Comment by tiamat2012** [comment]
Yeah that was it. The last build fixed it.  I found a few more issues though.  I will open new issues for them and close this one, since it is fixed.
