### ISSUE TITLE
Packs management error

### ISSUE THREAD

**Issue by tiamat2012** [crowbarmaster/BedrockManagementService#22]
Although I have 2 resource packs loaded in the latest release, the R/B pack manager says I do not have any (even though I can see they are actually loaded in the world when I play).  And I believe after loading that screen, the server becomes unresponsive to the client.  Even if you stop and restart the client, it will fail to connect.  You have to restart the service (which could also be why it crashes instead of stops cleanly).

**Comment by crowbarmaster** [comment]
This is a known issue that seems to occur with a handful of conditions. A new service, old server directory with installed pack(s), new server deployed over old, and the same pack(s) re-installed. It is easily explained as an oversight to how my reference file is fetched from the server directory, which in this case will grab it with packs known already. I plan to implement a way to build this file and server props every time a new version is fetched, for accuracy. A work-around is to remove the(se) pack(s) from the stock_packs.json file, found in the Server folder.

**Comment by tiamat2012** [comment]
Pack manager now shows installed packs (even called out that I have 2 versions of the same pack, which after deeper inspection was actually the case and I didn’t notice).  I removed one of the duplicates using the pack manager and that worked great!
