### ISSUE TITLE
Deletion of a backup does not refresh the listing

### ISSUE THREAD

**Issue by tiamat2012** [crowbarmaster/BedrockManagementService#23]
When you delete a backup in the client, it does not refresh the listing.  It does actually delete the backup.  Closing and opening the Backup manager screen does show that the backup was deleted.

**Comment by crowbarmaster** [comment]
Commit 1c8d490a0111ed66c023135dfec4a837c5fbe36f should take care of this! This has shipped in 2.56.8031.134.

**Comment by tiamat2012** [comment]
2.56.8031.12492 refreshed the list after deletion of a backup.
