### ISSUE TITLE
Security warnings for download/install

### ISSUE THREAD

**Issue by tiamat2012** [crowbarmaster/BedrockManagementService#24]
I know this may just be the beta/latest files you are building, but they do throw warnings on download and install about untrusted executables.  Downloading the "latest" is actually a multi-step process, one to allow the download of an exe to work (you have multiple screens to click to allow it to even happen), and then when you run the exe you have to trust the source.  Hopefully when you are ready to build public releases, you could sign them or at least get them scanned and white listed so they do not generate security warnings.

Also - I am glad to see you added version info in the exe files (File -> Properties -> Details tab).  For "latest" builds, could you could use the date/time of the build or commit string?  I may accidentally use an older version in testing because I really cannot easily tell them apart.

**Comment by crowbarmaster** [comment]
I have effectively taken care of versioning now, Compiler will provide build/revision numbering to create unique versions. Trusting/signing is likely only because I am uploading as executables. I will get back to working on my GH Action script to zip the files up before uploading, and that should subside the warnings once again. Once things pan out a bit more, I will look into getting them signed properly.

**Comment by crowbarmaster** [comment]
I tested with my server machine, and can download the latest zip archive without being pestered by untrusted sources. Latest version 2.56.8031.134 should satisfy this issue entirely!

**Comment by tiamat2012** [comment]
2.56.8031.12492 - MS Edge didn't ask me about downloading unsafe exe files since they are now packaged into a zip file, but when I extract and run the client exe, I do still get a warning message.

<img width="406" alt="image" src="https://user-images.githubusercontent.com/16579793/147519610-717f8124-b5c7-4a3a-8909-1af023984976.png">

You have to click More Info, and then you can click Run Anyway.

<img width="431" alt="image" src="https://user-images.githubusercontent.com/16579793/147519654-ca31bd10-ffad-4e37-8beb-a6443e2640df.png">

You probably won't be able to solve this unless you were to spend money to get a code sign cert, so don't go out of your way for me.  If your app became really popular and more people were concerned about the warning, then it might be worth it.

**Comment by tiamat2012** [comment]
If you submit the latest version here and it passes the scan, then the SmartScreen warning will go away fairly quickly.

https://www.microsoft.com/en-us/wdsi/filesubmission

You do have to submit each version of the binaries that you build.  Since there are no other open issues at the moment, now might be a good time to get it reviewed.  It doesn't cost you anything to have it reviewed (you do need a Microsoft account, which you probably do as a developer) and you can submit it as often as you want, but I wouldn't go too crazy here (just on releases posted in github and obviously not your personal local builds while you are actively coding).

See the TL;DR answer here for a lot more info on the other options.

https://stackoverflow.com/questions/48946680/how-to-avoid-the-windows-defender-smartscreen-prevented-an-unrecognized-app-fro

**Comment by crowbarmaster** [comment]
I had actually looked into this at some point, and I agree! I have decided, as you had mentioned, to scan to-be stable releases prior to their upload. Also as you mention, since we can safely close active issues, This is probably a good build to scan and mark stable! My task for tonight is to get that moving.

**Comment by crowbarmaster** [comment]
Good news! I have released version 2,6 today. These have been scanned by MS, and should not cause warnings! Closing the issue!
