### ISSUE TITLE
When saving global variables in GUI, Service crashes.

### ISSUE THREAD

**Issue by crowbarmaster** [crowbarmaster/BedrockManagementService#3]
When I changed the backup to true, the schedule, and the backup directory (using the client Edit Globaql Service settings button), when the background service restarted, the service log says:

> Error Starting BedrockServiceWrapper    at System.ServiceProcess.ServiceBase.RequestAdditionalTime(Int32 milliseconds)
>    at Topshelf.Runtime.Windows.WindowsServiceHost.Topshelf.HostControl.RequestAdditionalTime(TimeSpan timeRemaining)
>    at BedrockService.Service.Core.BedrockService.Start(HostControl hostControl) in C:\Users\Crowbar\source\repos\crowbarmaster\BedrockManagementService\BedrockService\Service\Core\BedrockService.cs:line 57
> 

I tried to do it again to see if I could repeat it, and unfortunately, this time the service went south.  I tried to stop the service with net stop, and its just sitting at "Stopping" - time for a reboot...  You might do some more testing with the background service trying to break things...

It's reproducable - just click Edit Global Service Settings, don't have to change anything, and then Save.  Reconnect once it restarts and you will see that error in the service log window option.  Once you do that, you cannot stop the background service anymore (without a reboot).

_Originally posted by @tiamat2012 in https://github.com/crowbarmaster/BedrockManagementService/issues/2#issuecomment-988420225_

**Comment by tiamat2012** [comment]
Positive news.  The backup did run on the schedule I set last night.  So even though the service had a problem during the client update of that file, when the server rebooted and the service restarted automatically, it did read the config correctly and run the backup per the schedule.  I cannot recall if I manually changed the Globals.conf file or if the client changed it correctly.

**Comment by crowbarmaster** [comment]
Yeah and that would be the expected part, as the new config is written before restarting the service. I had some time to look into this particular issue, and it seems my watchdog loop was still referencing an old variable, one that would cause an exception when it was terminated. Working on a solid fix for that now, will ship in next build!

**Comment by tiamat2012** [comment]
This bug is fixed in v2.53

**Comment by crowbarmaster** [comment]
Acknowledged and closing issue!
