### ISSUE TITLE
Duplicate resource pack references

### ISSUE THREAD

**Issue by tiamat2012** [crowbarmaster/BedrockManagementService#32]
I was checking to see if you backed up the global_resource_packs.json file (yep - will close that ticket!), and I noticed that I have both my resource packs listed twice (4 items in the top-level array).  That's probably somehow my fault for adding them a second time in the client because I wasn't sure if they were added when I copied my world from Windows 10 back to the server, but you should check to see if a pack is already listed when someone attempts to add them, and do not duplicate entries.  I haven't really tested the resource pack manager all that much, other than adding the pack(s) upon world creation.

**Comment by crowbarmaster** [comment]
This is related to issue #22 from the sounds of it. A new service was trained to adopt a servers valid_known_packs.json to use as reference. Not thought of till later but the end result is using an old server with packs, then using a brand new service will cause this issue found here. The next release should include a method to build all referenced files from a newly fetched build. This will also keep issues with server.properties growing again becoming an active issue.

**Comment by tiamat2012** [comment]
I tried to add a pack via the pack manager that was already installed, and it didn't create a duplicate entry in the json file.  I don't have a reason to copy the worlds back to the Windows 10 system and try recreating the problem.  If you feel that this problem is fixed, you can close the ticket.

**Comment by crowbarmaster** [comment]
Sounds good! I will close this!
