### ISSUE TITLE
Backups should include installed packs.

### ISSUE THREAD

**Issue by crowbarmaster** [crowbarmaster/BedrockManagementService#35]
Now that pack management is working better, I believe I should take it a step further and include installed pack files with backups. These can easily be restored on rollback to ensure that nothing within a server ends up broken, or to ensure that playing with a new/updated pack can be reversed. I would like to augment backups to the point of snapshot restorability. This would mean that backups contain the configurations, and all files not found in a vanilla build. The backup manager will have a selection on rollback to also rollback configs or packs, giving control to the option.

**Comment by tiamat2012** [comment]
The manual backup did include a new folder with ZIP files for the 2 packs that were installed in the world.  I deleted one of the resource packs using the pack manager, verified the resource pack was deleted from the server, and then restored the server from the backup.  It added the delete pack back to the server correctly.  So I think this one is good to go!

**Comment by crowbarmaster** [comment]
With your verification on this, I will close this!
