### ISSUE TITLE
Second client start and connect crashes service

### ISSUE THREAD

**Issue by tiamat2012** [crowbarmaster/BedrockManagementService#41]
When I was testing the client service reconnect issue, I accidentally started a second client (the first was still connected but minimized, so I didn’t notice it).  When I went to connect, the client sat there trying.  I went back to Services, and refreshed, and the service was not running (I assume crashed).  That’s when I noticed the second client in the task bar.

I was able to recreate the problem.

**Comment by crowbarmaster** [comment]
This bug has been on my mind for a while. I have added a block condition, and now accept dead clients to immediately close them, creating desired behavior. Patch will be in next release!

**Comment by tiamat2012** [comment]
Appears pretty solid now.  I tried a few scenarios and didn't have any problems.
