### ISSUE TITLE
Backup limit issue, not deleting oldest versions, overwriting newest backup

### ISSUE THREAD

**Issue by tiamat2012** [crowbarmaster/BedrockManagementService#42]
Hi!

Yesterday I had reached the max 10 backups (I changed it to 10, the default is 25).  However, when I make a new backup manually or via the scheduler, the newest backup is removed, not the oldest.  Which means I cannot restore a slightly older version anymore.  I have to manually delete the oldest backup to make a new backup that doesn’t overwrite the last one.

This happens with the scheduled backup as well.  I lost the Jan 2 backup, which was overwritten by the Jan 3 backup.

**Comment by crowbarmaster** [comment]
Found the cause of the bug, and patched it. Fix will be in new release shortly!

**Comment by tiamat2012** [comment]
Manual backup deleted the oldest instead of newest, so this bug is verified fixed.
