### ISSUE TITLE
Enhancement: Add client setting for auto-scroll on client start

### ISSUE THREAD

**Issue by tiamat2012** [crowbarmaster/BedrockManagementService#43]
Hi!

I always end up checking the Lock scrollbar to end box so I can see the last messages on a long running server (like performing an on demand backup).  Perhaps add a setting to the client config screen that sets this value on open to checked or unchecked?

Thanks!

**Comment by crowbarmaster** [comment]
Absolutely can! This has been implemented and I will push a new release shortly. Thanks man!

**Comment by tiamat2012** [comment]
Works great!
