### ISSUE TITLE
Update readme.

### ISSUE THREAD

**Issue by crowbarmaster** [crowbarmaster/BedrockManagementService#47]
Readme is far out of date now and needs updating. I plan to start working on wiki pages to make navigation easy.

**Comment by mhensler** [comment]
It would be good to include a section on importing an existing server/world into Bedrock Service Management.

**Comment by mhensler** [comment]
@crowbarmaster Would you like some help updating documentation?

**Comment by crowbarmaster** [comment]
> @crowbarmaster Would you like some help updating documentation?

I suppose I wouldn't mind that, my time is fairly limited these days and I try to spend what I can on the code. I would say its been out of date this long now - perhaps it would be best to hold off till the next release rolls out, since it plans to change a bit of structure. I would hate to have you write something that becomes obsolete soon afterwards. I have a couple days off a week, I should have it done next week! I appreciate you help man!
