### ISSUE TITLE
R/B Pack manager, Client hangs on pack request.

### ISSUE THREAD

**Issue by crowbarmaster** [crowbarmaster/BedrockManagementService#5]
I added 2 mcpacks to the world using the R/B Pack Manager and that worked fine (I selected them both from my Downloads folder and uploaded them, since you cannot browse and add one at a time - possible a minor bug to look at later).  Afterward, when you click the R/B Pack Manager button, the server side log shows the 2 packs being found, but the client side hangs and doesn't show the pop-up window.  You have to kill it with Task Manager or from the start bar -> Close Window.  
...

_Part of post originally posted by @tiamat2012 in https://github.com/crowbarmaster/BedrockManagementService/issues/2#issuecomment-988409823_

**Comment by crowbarmaster** [comment]
Turns out this is due to DirectoryInfo no longer being marked with the [Serializable] attribute in .NET Core. I reworked much of this to suit the new changes, and so far works well. Needs more time debugging and, with the shift to 1.18, the addons I had been testing with appear to be broken now. I need to find new ones that work lol. None-the-less, these updates will ship in the next beta!

**Comment by tiamat2012** [comment]
I am using the Invisible Tweaks and Brewing Guide UI resource packs for 1.17 and they seem to be working fine in 1.18.2.  Both are just modifying some visual aspects of the game and nothing to specific to 1.17 or 1.18 code changes.

**Comment by crowbarmaster** [comment]
R/B Pack manager has been cleaned up quite a bit, and works smoothly now! I have a decision to make regarding sending world packs to the server; whether or not I should list Worlds in the list, or automatically change the active world to match the last sent world. I feel like the latter will do, as I don't feel like it would be intentional to send multiple worlds to one server. Your thoughts?

**Comment by tiamat2012** [comment]
I cannot run more than one world on a server, as the Xbox will only find a server on the default ports.  That's another reason why I run VM's.  I can easily spin up a Windows server for each world on it's own IP address.  Which makes the client convenient in managing multiple servers with 1 world each on them.

**Comment by tiamat2012** [comment]
R/B Pack Manager no longer hangs on open when packs are installed on the server.  So the initial reported bug is fixed in v2.53

**Comment by crowbarmaster** [comment]
Acknowledged and closing issue!
