### ISSUE TITLE
Server information box-Fill with information.

### ISSUE THREAD

**Issue by crowbarmaster** [crowbarmaster/BedrockManagementService#54]
The server information box is the textbox left of the server select list. As it is now, it simply reflects the selected server's name. This should be filled with information regarding the current server's status. Things that immediately come to mind would be an uptime, player count, and last backup status. Feel free to add your thoughts on what would be useful!

**Comment by tiamat2012** [comment]
That sounds like a good use of that space.  Would it refresh the data every so often (since player counts could be a little more dynamic) while the client is connected, sort of like a free keep-alive ping?  This could also show the state of the server being manually stopped (even though the service is still running) for that other FR.

**Comment by crowbarmaster** [comment]
> That sounds like a good use of that space. Would it refresh the data every so often (since player counts could be a little more dynamic) while the client is connected, sort of like a free keep-alive ping? This could also show the state of the server being manually stopped (even though the service is still running) for that other FR.

Yes it would! I'm thinking about a two-second cycle would be appropriate, as it will of course request the information when changing the server in the list to start off. I actually started work on the stop feature request, and that is indeed a use for that box already 😄. I am also going to push the buttons together a bit, and adding a few dummy buttons for now in case we should discover an upcoming use for them.

**Comment by demifiend9** [comment]
World size? And maybe also total backup size for disk usage of all backups for that server.

**Comment by crowbarmaster** [comment]
> World size? And maybe also total backup size for disk usage of all backups for that server.

Perhaps I could work that in down the road! I would need to keep a record containing this information from the last known backup, iterating files every couple seconds is costly. Servers without a backup will simply display N/A.

**Comment by crowbarmaster** [comment]
I have done some work to this, and I believe you will be happy with the results! Feel free to open a discussion/issue if you think of anything else! Closing this now! I still need to add the server uptime, but with the recent developments, my attention was refocused. I will still work this in at some point!! Closing this for now!
