### ISSUE TITLE
Bug: Client Logs created in wrong directory

### ISSUE THREAD

**Issue by demifiend9** [crowbarmaster/BedrockManagementService#58]
I have service and client executable in `D:\Bedrock\BMS` and Service and Servers logs are correctly put in their respective folder in `D:\Bedrock\BMS\Logs\`

However, Client logs are put in `D:\Logs\Client`, they should be in `D:\Bedrock\BMS\Logs\Client`

**Comment by crowbarmaster** [comment]
I will take a look! For reference sake, what version were you using? Either way, I will verify that the latest client picks up the base directory like it should. Thank you!

**Comment by demifiend9** [comment]
Version 2.6.RC2

**Comment by crowbarmaster** [comment]
So far, I have not seen any issues come up like this in any recent tests. Last log I have in this path is from the 1st of the month, its safe to say this should no longer happen! Closing issue!
