### ISSUE TITLE
UI Tweaks in Player Manager

### ISSUE THREAD

**Issue by mhensler** [crowbarmaster/BedrockManagementService#59]
- Change the "Permission" fields to select boxes
- Change the "Whitelist" and "Ignore max player" fields to checkboxes or select boxes

**Comment by crowbarmaster** [comment]
Hello and thank you! This has been on the backburner for a while, and I do my best to ship this in the next dev build!

**Comment by crowbarmaster** [comment]
So far it looks like this!

![image](https://user-images.githubusercontent.com/69368213/151895060-19c247bd-81fb-480e-adb7-5534a3a117e4.png)

I will verify it works well, along with fixing other open issues related to Player Manager, and will ship in the next release!

**Comment by mhensler** [comment]
That looks great. Thanks, @crowbarmaster!

**Comment by crowbarmaster** [comment]
Much testing has gone into this, and seems to work very well! Re-open a new issue if anything arises! Thanks!
