### ISSUE TITLE
Bug: Negative values for Time spent in game

### ISSUE THREAD

**Issue by mhensler** [crowbarmaster/BedrockManagementService#60]
The "Time spent in game" field in Player Manager shows negative values until users disconnect from their first session.

![image](https://user-images.githubusercontent.com/1815504/151680378-0fbee656-cab9-4ce0-a791-ab0e66152007.png)

**Comment by crowbarmaster** [comment]
I will take care of this in the upcoming update! Thanks!

**Comment by crowbarmaster** [comment]
Procedures have been added to detect odd time scenarios,

Player created via GUI, but never connected:
![image](https://user-images.githubusercontent.com/69368213/151898063-780f1e96-2538-41fa-b426-8309c0b6d34e.png)

Player currently in server:
![image](https://user-images.githubusercontent.com/69368213/151898254-3d10d43f-0df3-45ea-8bb4-69133789c4de.png)

Should take care of negative numbers displayed! Re-open an issue if anything else comes up after in the next build!
