### ISSUE TITLE
Bug: Ignore Max Player field is set to True automatically on service restart

### ISSUE THREAD

**Issue by demifiend9** [crowbarmaster/BedrockManagementService#61]
I manually set them to false in Player Manager but they revert back to true on service restart.

Version 2.6.RC2

**Comment by crowbarmaster** [comment]
I will check this out! Thanks again!

**Comment by crowbarmaster** [comment]
Confirmed! Simple fix, will be shipped shortly! Thanks man!

**Comment by crowbarmaster** [comment]
Confirmed issue is now fixed. Closing issue.
