### ISSUE TITLE
Enhancement: Command history

### ISSUE THREAD

**Issue by mhensler** [crowbarmaster/BedrockManagementService#62]
Please, consider adding command history.

**Comment by crowbarmaster** [comment]
This could be a possibility. A couple restrictions to this I will point out immediately: First, this will have to belong to the client, and cannot be stored with the server or service configurations. Second, commands recalled will be indiscriminate of the server it ran on and more a generic list. Give me some time, this is a great idea and will be implemented. However I feel there are much more pressing needs for this before small touchups like this can happen. Thanks man!

**Comment by mhensler** [comment]
Another idea (additional or alternative) would be to have a user-curated list of commands. Users could add/edit/remove commands from a list and select a command from a dropdown to execute on the connected server.

**Comment by demifiend9** [comment]
> Another idea (additional or alternative) would be to have a user-curated list of commands. Users could add/edit/remove commands from a list and select a command from a dropdown to execute on the connected server.

That's a really good idea. Have a list of common commands (mostly related to gamerule) included with the client and make them editable so you can add/remove. In past I have used a different server manager which had [some commands built in](https://github.com/BaoUida2000/Minecraft-Bedrock-Server-Manager/raw/master/app_screenshot.png).

**Comment by crowbarmaster** [comment]
> Another idea (additional or alternative) would be to have a user-curated list of commands. Users could add/edit/remove commands from a list and select a command from a dropdown to execute on the connected server.



> > Another idea (additional or alternative) would be to have a user-curated list of commands. Users could add/edit/remove commands from a list and select a command from a dropdown to execute on the connected server.
> 
> That's a really good idea. Have a list of common commands (mostly related to gamerule) included with the client and make them editable so you can add/remove. In past I have used a different server manager which had [some commands built in](https://github.com/BaoUida2000/Minecraft-Bedrock-Server-Manager/raw/master/app_screenshot.png).

Both are excellent ideas! I like the idea of user-generated lists, but to add them both and have them function together, how would you like to see that? For example, if you click on the box and start typing, you will get auto-complete from your list, however clicking on the box and hitting the up arrow will toss a list box of history above it to scroll through. If you think of some way that would function better, I am all ears!

**Comment by mhensler** [comment]
> Both are excellent ideas! I like the idea of user-generated lists, but to add them both and have them function together, how would you like to see that? For example, if you click on the box and start typing, you will get auto-complete from your list, however clicking on the box and hitting the up arrow will toss a list box of history above it to scroll through. If you think of some way that would function better, I am all ears!

Oooh, I like that.

> Edit: Would We need a new box for this? possibly a full-screen extension? I feel the main window should resist getting much larger. Perhaps I will look into compacting the UI some. I have been thinking that perhaps many of the button functions could stem out of a context menu from a "Server actions" or "Service actions" button.

I wouldn't mind a menu.

**Comment by crowbarmaster** [comment]
As of this point in time, I no longer have the ability to add this. It's still a wonderful idea, and if someone needs some one-on-one help getting started, as well as a look inside my head, I'd be glad to set up a time to do so!
