### ISSUE TITLE
Enhancement: Command auto-completion

### ISSUE THREAD

**Issue by mhensler** [crowbarmaster/BedrockManagementService#63]
Please, consider adding command auto-completion (or at least, context-aware usage/syntax help).

**Comment by tiamat2012** [comment]
Hmm.  That might be quite technically challenging, as you would have to pass keystrokes from client to service, and the service to bedrock server, and then try to capture all the text that is echoed back to the screen for every keystroke.  I believe today the code sends the whole line and a return mark, and then captures what is returned within a short time period back to the client.  It’s quite different on the backend than typing directly into the chat line in Minecraft.  Alternatively, the client would need awareness of the entire command line structure to do auto complete locally, and that may cause syntax issues (you would have to know the syntax for all the different versions of bedrock that people may want to run).

**Comment by crowbarmaster** [comment]
@tiamat2012 spells it out well here (Thanks man). This aims to be used remotely, therefore I try to keep the networking traffic down as best as possible. This would need to be far more responsive than I would ever allow. Also as mentioned, there is no simple way to collect the current command list and attributes for each new version that rolls out. If the Mojang team would produce a CSV or similar, this would be easy. I will leave this open for now for your acknowledgement, but I will have to say this is a little beyond the scope of my available time and willingness. I appreciate your input though, and keep at it!
