### ISSUE TITLE
Enhancement: High DPI display support for client.

### ISSUE THREAD

**Issue by demifiend9** [crowbarmaster/BedrockManagementService#67]
My device has high resolution display with 200% scaling.

This is how client looks normally 
![no](https://user-images.githubusercontent.com/13422602/152150733-8c20d4c3-4ed4-4af0-83b6-a2540cde0c99.png)

If I go to properties>compatibility>change high dpi>override display scaling by Application it looks much better, but server and service logs aren't readable.
![yes](https://user-images.githubusercontent.com/13422602/152151068-45c90643-1294-47fc-a8a3-052decd52278.png)

Client logs however look great
![yess](https://user-images.githubusercontent.com/13422602/152151237-a29de1e0-1d71-41ee-ad8f-64ba204f5fa0.png)

**Comment by crowbarmaster** [comment]
So this was a very strange issue brought to you by Microsoft Bug Studio, where if I change displays (Remoted into from laptop in another room, not unusual), a forced desktop rescale would cause Forms Designer to rescale my Forms for me, and totally messed up the GUI yesterday. What you see now is a few hours of resetting sizes, paddings, and margins on all of the controls. What a nightmare. Interior padding (Mind you, these values were never modified by my hands) had some 9x13 value, and this would cause the full-size textbox to wrap out of view. Thanks for the catch! I had to change my own scaling settings to see this... I will push a fix build to this soon!

**Comment by crowbarmaster** [comment]
New build uploaded to fix the bug. I will consider looking into responding to scaling changes, though I have a feeling that much of that is a flaw with Forms integration in to .NET Core, or just the fact that Forms is a bit outdated. I'm sure I will be bored enough at work to do this research someday soon, lol.

**Comment by crowbarmaster** [comment]
Found a method today that .NET Core uses to set WinForms DPI modes. I have enabled what looks to be the best option for this setting, the next build may look different for you! I am not high-res and unfortunately do not have the grounds for testing.

**Comment by demifiend9** [comment]
I'd be happy to test although I'm not sure if there's anything to improve in this regard. The last few versions already look perfect. The only thing is I had to turn on application scaling by going to compatibility settings which should be on by default.

**Comment by crowbarmaster** [comment]
I wanna pop a post here at @demifiend9 , Just to see if the latest build doesn't make or break something related to this?

**Comment by demifiend9** [comment]
It looks great by default! No problems related to this.
