### ISSUE TITLE
Service installation needs attention

### ISSUE THREAD

**Issue by crowbarmaster** [crowbarmaster/BedrockManagementService#7]
With the core capabilities working in a CMD window, I thought I would go ahead and set it up as a background service.  I ran:

> BedrockService.Server.exe install

It started the server and then installed the service.  I pressed Control-C to stop the server, and then ran net start bedrockservice to start up the background service.  After that, it seemed to work fine.  I think you just need to catch the install command line option and not start the server.  The uninstall option had a slightly more strange output and also required a Control-C to end the program, but I think it also was trying to start the server.

_Part of a post originally posted by @tiamat2012 in https://github.com/crowbarmaster/BedrockManagementService/issues/2#issuecomment-988409823_

**Comment by crowbarmaster** [comment]
So it does appear to try to start the service, as you will see configurations loading. However the actual service loop doesn't execute. It still hung up after TopShelf finished as part of TopShelf design. I reconfigured TopShelf's setup to acknowledge successful install/uninstall and automatically exit afterwards. It should be noted that if something should go wrong with either operation, it will still hang as a way to provide info. Doesn't appear to be much I can do here. I have some cleanup to do, and the beta will be up shortly!

**Comment by tiamat2012** [comment]
It works.  Some of the output is a little confusing, but it did install/install the service and exit now. So the bug is fixed in v2.53.

**Comment by crowbarmaster** [comment]
Acknowledged and closing issue!
