### ISSUE TITLE
Bedrock updates to `allowlist.json`

### ISSUE THREAD

**Issue by crowbarmaster** [crowbarmaster/BedrockManagementService#71]
New message in server startup today:

`'whitelist.json' will be deprecated. Please migrate to 'allowlist.json'.` 

says I have some work to do. I will get some research in on this subject and see what needs to be done.

**Comment by tiamat2012** [comment]
It might just be a naming problem, because of the racial connotations.  A lot of software that used allow and deny lists were using color references.

**Comment by crowbarmaster** [comment]
Correct, it's both the file name, and the bool property in server.properties. Since I don't handle the props directly anymore, I have done quite a bit to verify the use of the correct configurations. I will close this now!
