### ISSUE TITLE
BMS Client fails to start

### ISSUE THREAD

**Issue by tiamat2012** [crowbarmaster/BedrockManagementService#76]
Hi @crowbarmaster, its been a while, but I finally had some time to revisit this software and try it out again.

Unfortunately, the client won't even start on my Windows server.  Looking at event viewer, I see these errors:

Faulting application name: BedrockService.Client.exe, version: 2.6.8093.31951, time stamp: 0x61e1d8d9
Faulting module name: KERNELBASE.dll, version: 10.0.17763.2452, time stamp: 0xad1c2e55
Exception code: 0xe0434352
Fault offset: 0x0000000000039319
Faulting process id: 0x58c
Faulting application start time: 0x01d832879e26a029
Faulting application path: C:\Minecraft\BDServer\BedrockService.Client.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 9e37a0f5-d59a-4fd1-9d90-9d29f6ff0ff5
Faulting package full name: 
Faulting package-relative application ID: 

Application: BedrockService.Client.exe
CoreCLR Version: 6.0.21.52210
.NET Version: 6.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException: Could not load file or assembly 'System.Windows.Forms, Version=6.0.2.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'System.Windows.Forms, Version=6.0.2.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

I tried both of these versions, with the same error:

BedrockService.Client.exe
2.6.8093.31951

BedrockService.Client.exe
2.6.8089.1944

I thought it might be something to do with .NET, but I did a Windows update and after the update for .NET, it didn't resolve the error.

Trying to start the 2.6.8093.31951 service, and I get this error on first run:

<img width="345" alt="image" src="https://user-images.githubusercontent.com/16579793/157144787-863d33c0-6944-4ffe-867f-58a41fea7642.png">

It looks like some of the files were moved around to their new locations, but something died in the migration.  I attempted to start the service again, and it finished creating some of the files, and started the service.  Manually looking at the service log, and it did upgrade the Minecraft server version, even though I set the SelectedServerVersion=1.18.2.03 in both the Service.conf file and the BmsConfig\ServerConfigs\world.conf.  But perhaps I need to really make those changes via the client.

Anyway, I wonder if anyone else is having problems. Perhaps it's just a Windows 2019 server problem and works ok on Windows 10/11?

**Comment by tiamat2012** [comment]
I did try running the client in a new folder to simulate a clean install, same error.

**Comment by crowbarmaster** [comment]
Hey man! Hope things are well!

I started by downloading a copy locally to my laptop right from GH. It seems to launch as expected.... I will fire up my Server 2019 VM in a bit and give it a go! As for the service, Sounds like perhaps it was something that happened launched as a service. I had done testing in this manner, but perhaps I missed testing something near the end. I should have time Thursday to pinpoint that issue!

**Comment by crowbarmaster** [comment]
Update: After a small fight getting VBox to work on my main machine, I gave up and installed a fresh copy of the latest vbox, followed by a fresh copy of server 2019, .NET Desktop and hosting runtimes. I grabbed the latest copy of the client, and it fired right up. I am at a loss here, unfortunately. NET Core and WinForms is getting worse to work with. Way too many odd-ball issues, lol.

**Comment by tiamat2012** [comment]
Let me try looking at the .NET versions I have installed tomorrow and if they need to be updated.  I can live with a “just me” problem and try to figure it out.
