### ISSUE TITLE
Superficial spelling fix

### ISSUE THREAD

**Issue by tiamat2012** [crowbarmaster/BedrockManagementService#77]
I was hesitant to even mention it, but you have a minor spelling error in the smaller server status screen on the right side of the client:

Total service-wide bakups

An easy fix to check into git now so it gets included when you have other updates to make in the future.

**Comment by crowbarmaster** [comment]
Wow! I gotta say I am usually pretty good about fixing these before too long.... this one totally got past me lmao.... Thanks for that man!

**Comment by crowbarmaster** [comment]
Closing, pushed in latest build!
