### ISSUE TITLE
AutoBackupsContainPacks function

### ISSUE THREAD

**Issue by tiamat2012** [crowbarmaster/BedrockManagementService#78]
What is this supposed to do?

<img width="326" alt="image" src="https://user-images.githubusercontent.com/16579793/157340721-9e729b99-d06f-47b7-bc0f-9089b790c436.png">

I set it to true thinking it would backup the custom resource packs installed in the world, but I don't see anything different in the ZIP file backup created via the scheduled task.

**Comment by crowbarmaster** [comment]
Indeed it should! I will check on this Thursday as well! IIRC, I started working on a way to differentiate between manually triggered backups and automated ones, and in doing so simply haven't referenced this yet. Hopefully Thursday leaves me with time to work on that some more!
