### ISSUE TITLE
Server config window too wide

### ISSUE THREAD

**Issue by crowbarmaster** [crowbarmaster/BedrockManagementService#8]
Another very minor bug is the width of the server config edit screen.  Can you make the Value column slightly smaller in width so that when you enter in a value in that column, it doesn't scroll the window over so you cannot read the Entry names anymore.  I just have to resize that column slightly and it works better.  In simple terms, the scrollbar at the bottom of the window should not be visible when you first open the pop-up window.

_Part of a post originally posted by @tiamat2012 in https://github.com/crowbarmaster/BedrockManagementService/issues/2#issuecomment-988409823_

**Comment by tiamat2012** [comment]
This problem also appears in the Edit Global Service settings screen.  It does appear in the backup manager screen as well, but since you aren't editing the Values column, it's not a problem.

**Comment by crowbarmaster** [comment]
Lowering the width from 600 to 500 for the Value column. Now there is no clipping and the scroll bar is gone. Will ship in next beta. Nifty fact, all three of these menus re-use the same form 😄

**Comment by tiamat2012** [comment]
This bug is fixed in v2.53

**Comment by crowbarmaster** [comment]
Acknowledged and closing issue!

**Comment by tiamat2012** [comment]
@crowbarmaster I still get some clipping in this window...  I just installed the service on a Windows 10 system so I can run the world while on the go (on a Macbookpro with Bootcamp!), and it still forces the screen shift to the right so you cannot see the full Entry column anymore...

<img width="634" alt="image" src="https://user-images.githubusercontent.com/16579793/146467795-49354d2a-1bb6-4801-a664-9a18df5acb74.png">

**Comment by crowbarmaster** [comment]
So I have been noticing something strange with Windows forms lately, probably due to the way they handle Forms in .NET Core now. A change in aspect ratio seems to crop (or possibly stretch, even) the form's I spawn. I will need to do some research on the issue to dig up some dirt on what exactly is going on here, lol.
