### ISSUE TITLE
Max backup setting not working

### ISSUE THREAD

**Issue by tiamat2012** [crowbarmaster/BedrockManagementService#81]
Hi!

it’s been a while, and I hope everything is well with you!  I thought I would open a ticket or two for a few bugs that have been appearing recently.  This issue is the max backup not working as expected.  Having run the service for a while, I started having some issues with not being able to connect to the Minecraft server and I have to End Task both the Minecraft server and the service to get it back up.

I noticed that my server has a ton of backup files when the setting is set to 50.  I am not sure if that is causing the hang or the memory issue… see next issue…

![IMG_0378](https://user-images.githubusercontent.com/16579793/171760169-ef5eff5f-f03f-48ee-b0dd-4b539d9e13ce.jpeg)
![IMG_0379](https://user-images.githubusercontent.com/16579793/171760189-e0ee25d1-cb7e-4294-a601-f8edc783281a.jpeg)

**Comment by crowbarmaster** [comment]
Hello! It has been a while! I took on a new job that doesn't really leave me with much free time, so this basically got shoved aside for more important tasks. That being said, I will gladly investigate the issues at hand. I am going to assume that it's something that was overlooked during the transition from folders to archive files. I will run some tests and see what's up!

**Comment by crowbarmaster** [comment]
The commit above fully fixes this issue! This was one crucial element I had forgotten to update during the shift to zip files. My bad!
