### ISSUE TITLE
Implement no downtime backups

### ISSUE THREAD

**Issue by tiamat2012** [crowbarmaster/BedrockManagementService#9]
This is a feature request.  I cannot assign labels to these items, so please mark it appropriately.

In the C:\MCBedrockService\<world>\bedrock_server_how_to.html, there are 3 commands to do a live backup without stopping and starting the server.  I would like to see an option to do these backups as an alternative backup method to the stop-copy-start method (offer both options) in both the manual backup and in the scheduled backups.  I believe these options have been around for a while now, so it probably works with some older worlds too.

This will help some people who want to do more frequent backups during the day while players are online, or perhaps after someone builds something really cool and wants to manually back it up, but doesn't want to kick everyone off the server to do so.  And they still get the nightly backups when they may be doing the normal or full backups using the stop-copy-start method.

**Comment by crowbarmaster** [comment]
This is actually a planned feature to implement, along with pushing permissions, ops, and whitelist updates with interrupt-free operation. I believe the other commands are already in v2.5 and beyond, though I need to investigate this one further as to how and where backups are performed and stored. The biggest issue here is I would no longer have absolute control of the the backup path or folder name and current systems rely on this information. I realize the need for this however, and will figure something out for it sooner rather than later.

**Comment by tiamat2012** [comment]
Check the docs (very end of the html file I mentioned).  I don't think it's as hard as you imagine.  And you would still have complete control over the backups and files.  It's still a feature request, so you can work on it later.  Don't take this response as it being an urgent request or that you have to work on it now.

You can run these commands in the client manually and see what they return.  I did it to see what Minecraft returns.  The process would be:

1. run "save hold" and loop for a little bit running "save query" until you get a list of files - the wait time will depend on the size and number of the world database files
2. copy all the world files to a temp folder
3. run "save resume" to release Minecraft from writing the change logs at the end of the db files and applying the changes normally
4. go through the list from "save query" output and truncate the temporary copy to the lengths specified (the "hard" part, which actually isn't that hard in code)
5. create your ZIP file and copy it wherever you wanted
6. delete the temp files

Technically, I could run these steps manually and do a live backup with the bedrock client sending the commands.  The hardest part (which again isn't that hard) is writing a script that took in the save query output and truncating the files correctly.

**Comment by tiamat2012** [comment]
Alternatively, if you want to save space and not create a second copy of all the world files, you would:

1. run "save hold" and loop for a little bit running "save query" until you get a list of files - the wait time will depend on the size and number of the world database files
2. get the list of all files in the world folder and subfolders
3. for each file, read the file content into memory, truncate the data in memory if in the output of "save query" tells you to (otherwise copy the whole file as is), and then write/append that truncated memory file to the ZIP file using the ZipArchive.CreateEntry function.
4. run "save resume" to release Minecraft from writing the change logs at the end of the db files and applying the changes normally
That would prevent making a second copy of all the files in he temp folder.

**Comment by crowbarmaster** [comment]
Closing with latest commit satisfying issue! Will ship in next release!

**Comment by tiamat2012** [comment]
Hi.  Everything is working fine with 2.55.  I have a very tricky config running right now on a Mac bootcamp windows 10 setup at a hotel.  I haven’t been able to reply to any of your issues until tonight.  It took quite a while to get firewalls, ICS, a tiny Wi-Fi hotspot device, Xbox and iPads on the private Wi-Fi, and bridging/routing the hotel Wi-Fi to all work out just right, so I am not going to touch it and try 2.56 until I get back home.

The only gap is related to this issue.  The backup is working great with no downtime backups, but the world_*_packs.json files are not backed up or restored.  You could say this was a bug with the save query output not including this file, but when I restore a backup, the resource packs get deactivated.  I can manually restore this file from my own backup and restart the server, but ideally you could include these json files in the backup and restore process.
