### ISSUE TITLE
Issues starting service after new install

### ISSUE THREAD

**Issue by swangy** [crowbarmaster/BedrockManagementService#91]
I've successfully run the bedrock server from command line, but after installing it as a service it fails to start with error:
```
A system error has occurred.

System error 1064 has occurred.

An exception occurred in the service when handling the control request.
```

.Net Hosting bundle and desktop runtime both installed, client GUI launches but cant seem to get the service started.  any suggestions?

Edit: this is on windows server 2016

**Comment by crowbarmaster** [comment]
Issue was solved in GitHub, turned out to be the `AcceptedMojangLic` property in `Service.conf` was never set as it needs to be. Give this a go, and try that. I apologize for the delay!
